/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    teams: Team;
    'board-members': BoardMember;
    events: Event;
    'gallery-albums': GalleryAlbum;
    news: News;
    'legal-pages': LegalPage;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    mitgliedschaft: Mitgliedschaft;
    training: Training;
    eisstock: Eisstock;
    hero: Hero;
    'welcome-section': WelcomeSection;
    'location-section': LocationSection;
    footer: Footer;
    'kontakt-section': KontaktSection;
    'seiten-texte': SeitenTexte;
    'termine-section': TermineSection;
    'vorstand-section': VorstandSection;
    'news-section': NewsSection;
  };
  globalsSelect: {
    mitgliedschaft: MitgliedschaftSelect<false> | MitgliedschaftSelect<true>;
    training: TrainingSelect<false> | TrainingSelect<true>;
    eisstock: EisstockSelect<false> | EisstockSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'welcome-section': WelcomeSectionSelect<false> | WelcomeSectionSelect<true>;
    'location-section': LocationSectionSelect<false> | LocationSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'kontakt-section': KontaktSectionSelect<false> | KontaktSectionSelect<true>;
    'seiten-texte': SeitenTexteSelect<false> | SeitenTexteSelect<true>;
    'termine-section': TermineSectionSelect<false> | TermineSectionSelect<true>;
    'vorstand-section': VorstandSectionSelect<false> | VorstandSectionSelect<true>;
    'news-section': NewsSectionSelect<false> | NewsSectionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  slug: string;
  name: string;
  kategorie: 'Herren' | 'Damen' | 'Gemischt';
  kontakt: string;
  bild?: (number | null) | Media;
  ligaUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  titel: string;
  gruppe: 'fuehrung' | 'finanzen' | 'sport' | 'events' | 'technik';
  /**
   * Bestimmt die Reihenfolge innerhalb der Gruppe und auf der Startseite.
   */
  reihenfolge: number;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  telefon?: string | null;
  foto?: (number | null) | Media;
  /**
   * Die ersten 3 Markierten (nach Reihenfolge) erscheinen auf der Startseite.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  titel: string;
  datum: string;
  datumEnde?: string | null;
  /**
   * z.B. "10:00" oder "Ganztägig"
   */
  uhrzeit?: string | null;
  ort?: string | null;
  kategorie: 'Training' | 'Turnier' | 'Sonstiges';
  beschreibung?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  /**
   * z.B. "Rückblick 2024" — erscheint als Überschrift über dem Bilderraster.
   */
  titel: string;
  /**
   * Bestimmt die Reihenfolge: neuestes Jahr zuerst.
   */
  jahr: number;
  /**
   * Die Reihenfolge hier ist die Reihenfolge auf der Website.
   */
  bilder: (number | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  datum: string;
  titel: string;
  /**
   * Wird auf der Startseite unter der Überschrift angezeigt.
   */
  excerpt: string;
  /**
   * Wird aktuell noch nicht auf der Website angezeigt — eine Detailseite folgt in einem späteren Schritt.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bild?: (number | null) | Media;
  kategorie: 'Vereinsnews' | 'Vereinsleben' | 'Turnier' | 'Training';
  updatedAt: string;
  createdAt: string;
}
/**
 * Impressum, Datenschutzerklärung und Cookie-Seite. Diese drei Seiten können bearbeitet, aber nicht neu angelegt oder gelöscht werden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  /**
   * Fest verdrahtet — bestimmt die URL der Seite und kann nicht geändert werden.
   */
  slug: 'impressum' | 'datenschutz' | 'cookies';
  /**
   * Überschrift der Seite und Titel im Browser-Tab.
   */
  titel: string;
  /**
   * Optionaler Text direkt unter der Überschrift (wird auf der Cookie-Seite genutzt).
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Jeder Abschnitt erscheint als eigene Karte mit kleiner Überschrift darüber.
   */
  abschnitte?:
    | {
        titel: string;
        inhalt: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * z.B. "Stand: Juni 2026" — erscheint klein unter der Seite.
   */
  stand?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nachrichten aus dem Kontaktformular. Personenbezogene Daten — nur für angemeldete Benutzer sichtbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  /**
   * Wird vom aktuellen Formular nicht abgefragt.
   */
  telefon?: string | null;
  nachricht: string;
  einwilligung: boolean;
  einwilligungAm: string;
  gelesen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  kategorie?: T;
  kontakt?: T;
  bild?: T;
  ligaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  titel?: T;
  gruppe?: T;
  reihenfolge?: T;
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  telefon?: T;
  foto?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  titel?: T;
  datum?: T;
  datumEnde?: T;
  uhrzeit?: T;
  ort?: T;
  kategorie?: T;
  beschreibung?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  titel?: T;
  jahr?: T;
  bilder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  datum?: T;
  titel?: T;
  excerpt?: T;
  content?: T;
  bild?: T;
  kategorie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  titel?: T;
  intro?: T;
  abschnitte?:
    | T
    | {
        titel?: T;
        inhalt?: T;
        id?: T;
      };
  stand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  telefon?: T;
  nachricht?: T;
  einwilligung?: T;
  einwilligungAm?: T;
  gelesen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitgliedschaft".
 */
export interface Mitgliedschaft {
  id: number;
  hero: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    antragButtonLabel: string;
    /**
     * Wird vom Button im Hero heruntergeladen.
     */
    antragPdf?: (number | null) | Media;
    kontaktLinkLabel: string;
    kontaktEmail: string;
  };
  vorteile: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    titelHinten?: string | null;
    text: string;
    liste: {
      text: string;
      id?: string | null;
    }[];
    stats: {
      wert: string;
      label: string;
      zusatz: string;
      id?: string | null;
    }[];
  };
  dokumente: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    karten: {
      icon: 'users' | 'star' | 'fileText';
      titel: string;
      beschreibung: string;
      datei?: (number | null) | Media;
      downloadLabel: string;
      mailLabel?: string | null;
      mailAdresse?: string | null;
      mailBetreff?: string | null;
      id?: string | null;
    }[];
  };
  prozess: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    schritte: {
      nr: string;
      titel: string;
      text: string;
      id?: string | null;
    }[];
  };
  cta: {
    titel: string;
    text: string;
    buttonLabel: string;
    email: string;
    telefonLabel: string;
    /**
     * Wird als tel:-Link verwendet, z.B. "+4917225802099".
     */
    telefonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training".
 */
export interface Training {
  id: number;
  hero: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    buttonLabel: string;
    /**
     * Wird als tel:-Link verwendet, z.B. "+4917559049030".
     */
    telefonHref: string;
  };
  trainer: {
    eyebrow: string;
    foto?: (number | null) | Media;
    badge: string;
    name: string;
    rolle: string;
    /**
     * Leerzeile = neuer Absatz.
     */
    bio: string;
    fakten: {
      wert: string;
      label: string;
      id?: string | null;
    }[];
    telefonLabel: string;
    telefonHref: string;
  };
  angebote: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    karten: {
      icon: 'userCheck' | 'users' | 'trophy' | 'dumbbell' | 'star' | 'calendar';
      titel: string;
      beschreibung: string;
      id?: string | null;
    }[];
  };
  halle: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    stats: {
      wert: string;
      label: string;
      id?: string | null;
    }[];
    websiteLabel: string;
    websiteUrl: string;
    anrufLabel: string;
    telefonHref: string;
    standortTitel: string;
    /**
     * Jede Zeile wird als eigene Zeile ausgegeben.
     */
    adresse: string;
    kontaktTitel: string;
    kontaktText: string;
    kontaktTelefonLabel?: string | null;
    kontaktTelefonHref?: string | null;
    kontaktEmail?: string | null;
  };
  cta: {
    titel: string;
    text: string;
    buttonLabel: string;
    telefonHref: string;
    zurueckLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eisstock".
 */
export interface Eisstock {
  id: number;
  hero: {
    bild?: (number | null) | Media;
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    buttonLabel: string;
  };
  angebot: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    kacheln: {
      icon: 'mapPin' | 'users' | 'euro' | 'calendarDays';
      titel: string;
      beschreibung: string;
      id?: string | null;
    }[];
  };
  galerie?: {
    bilder?:
      | {
          bild?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  buchung: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    /**
     * Wird als Buchungs-Widget (iframe) eingebunden.
     */
    widgetUrl: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  headline: string;
  subtext: string;
  /**
   * Der Button verlinkt immer auf /mitgliedschaft.
   */
  ctaLabel: string;
  /**
   * Querformat, mindestens 1920×1080. Ohne Bild bleibt die Fläche grau — die Seite bricht nicht.
   */
  bild?: (number | null) | Media;
  /**
   * Laufen als Endlosband unter dem Text durch.
   */
  partnerLogos?:
    | {
        logo?: (number | null) | Media;
        /**
         * Leer lassen = Alternativtext des Bildes wird verwendet.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-section".
 */
export interface WelcomeSection {
  id: number;
  eyebrow: string;
  headline: string;
  intro: string;
  /**
   * Vier Kacheln passen genau in eine Zeile.
   */
  stats?:
    | {
        icon: 'trophy' | 'users' | 'mapPin' | 'zap';
        wert: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ohne Bild bleibt die Fläche grau.
   */
  bild?: (number | null) | Media;
  bildBadge: string;
  /**
   * Absätze durch eine Leerzeile voneinander trennen.
   */
  text: string;
  signaturName: string;
  signaturRolle: string;
  /**
   * Der Button verlinkt immer auf /mitgliedschaft.
   */
  ctaLabel: string;
  /**
   * Verlinkt auf /training. Der Pfeil wird automatisch angehängt.
   */
  sekundaerLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-section".
 */
export interface LocationSection {
  id: number;
  eyebrow: string;
  headlineTeil1: string;
  headlineTeil2: string;
  intro: string;
  /**
   * Der Button verlinkt immer auf /mitgliedschaft.
   */
  ctaLabel: string;
  /**
   * Fünf Karten passen am besten in das Raster.
   */
  karten?:
    | {
        titel: string;
        /**
         * Zeilenumbrüche bleiben erhalten.
         */
        untertitel?: string | null;
        /**
         * Ohne Bild bleibt die Fläche grau.
         */
        bild?: (number | null) | Media;
        /**
         * Externe Links (beginnen mit "http") öffnen in einem neuen Tab und liegen hinter der Google-Maps-Einwilligung. Interne Links beginnen mit "/", z. B. /eisstock.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Diese Daten erscheinen im Footer jeder Seite, im Instagram-Banner und im Kontaktbereich der Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  vereinsname: string;
  beschreibung: string;
  strasse: string;
  plz: string;
  ort: string;
  email: string;
  /**
   * Steht im Kontaktbereich über der Nummer, z. B. "Vorsitzender".
   */
  telefonLabel: string;
  telefon: string;
  /**
   * Technische Schreibweise, z. B. "tel:+491722580209".
   */
  telefonHref: string;
  kontaktpersonen?:
    | {
        label: string;
        name: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  funFactTitel: string;
  funFact: string;
  shop: {
    textVor: string;
    linkText: string;
    url: string;
    textNach: string;
  };
  instagram: {
    /**
     * Mit @, z. B. "@hardtertv".
     */
    handle: string;
    url: string;
    ctaEyebrow: string;
    ctaHeadline: string;
    /**
     * Der Instagram-Name wird automatisch dahinter gesetzt.
     */
    ctaText: string;
  };
  /**
   * Das Jahr wird automatisch eingesetzt.
   */
  copyrightName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Adresse, Telefon und E-Mail stammen aus „Footer & Kontaktdaten“ — hier stehen nur die Texte dieses Abschnitts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-section".
 */
export interface KontaktSection {
  id: number;
  eyebrow: string;
  headlineTeil1: string;
  headlineTeil2: string;
  intro: string;
  /**
   * In Google Maps: Teilen → Karte einbetten → die Adresse aus dem src="…" kopieren. Die Karte wird erst nach Cookie-Einwilligung geladen.
   */
  mapsEmbedUrl: string;
  mapsTitel: string;
  erfolgTitel: string;
  erfolgText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Überschriften und Einleitungen der Unterseiten. Die Inhalte selbst (Vorstandsmitglieder, Termine, Bilder, Mannschaften) werden in den jeweiligen Sammlungen gepflegt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seiten-texte".
 */
export interface SeitenTexte {
  id: number;
  vorstand: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    /**
     * Die Zahl wird automatisch davorgesetzt, z. B. "17 Mitglieder".
     */
    badgeSuffix: string;
    /**
     * Reihenfolge der Zeilen = Reihenfolge der Abschnitte auf der Seite. Gruppen ohne Mitglieder werden nicht angezeigt.
     */
    gruppen: {
      gruppe: 'fuehrung' | 'finanzen' | 'sport' | 'events' | 'technik';
      titel: string;
      beschreibung: string;
      id?: string | null;
    }[];
    ctaTitel: string;
    ctaText: string;
    ctaButtonLabel: string;
    ctaEmail: string;
  };
  kalender: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    monatsansichtLabel: string;
    listenansichtLabel: string;
    filterAlleLabel: string;
    ausgewaehlterTagLabel: string;
    naechsteTermineLabel: string;
    keineTermineTag: string;
    keineTermineListe: string;
    /**
     * Steht hinter jeder Uhrzeit, z. B. "Uhr".
     */
    uhrzeitSuffix: string;
  };
  galerie: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    /**
     * Die Zahl wird automatisch davorgesetzt, z. B. "84 Bilder".
     */
    bilderSuffix: string;
    leerText: string;
  };
  mannschaften: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    /**
     * Beschriftungen für die drei Reiter. Die Zuordnung der Teams passiert in der Sammlung Mannschaften.
     */
    kategorien: {
      kategorie: 'Herren' | 'Damen' | 'Gemischt';
      reiterLabel: string;
      listenEyebrow: string;
      /**
       * Die Zahl wird automatisch davorgesetzt, z. B. "9 Herren-Teams".
       */
      badgeSuffix: string;
      id?: string | null;
    }[];
    /**
     * Die Zahl wird automatisch davorgesetzt, z. B. "9 Teams".
     */
    teamsSuffix: string;
    kartenUntertitel: string;
    kontaktEyebrow: string;
    kontaktTitelVorne: string;
    kontaktTitelHighlight: string;
    kontaktText: string;
    kontaktLabel: string;
    kontaktTelefon: string;
    /**
     * Technische Schreibweise, z. B. "tel:+4915153553355".
     */
    kontaktTelefonHref: string;
    kontaktEmail: string;
  };
  mannschaftDetail: {
    zurueckLabel: string;
    saisonLabel: string;
    vereinBadge: string;
    verbandBadge: string;
    ligaEyebrow: string;
    ligaTitel: string;
    /**
     * Erscheint als "<Mannschaft> – <Angabe>" und zusätzlich in der Seitenbeschreibung für Suchmaschinen.
     */
    ligaSaisonLabel: string;
    ligaQuelle: string;
    abschlussText: string;
  };
  rechtliches: {
    zurueckLabel: string;
    cookiesEyebrow: string;
    /**
     * Wird ohne Leerzeichen an den zweiten Teil gehängt (aktuell "Cookie-" + "Einstellungen").
     */
    cookiesTitelVorne: string;
    cookiesTitelHighlight: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine-section".
 */
export interface TermineSection {
  id: number;
  /**
   * Die Jahreszahl wird automatisch angehängt.
   */
  eyebrow: string;
  headlineTeil1: string;
  headlineTeil2: string;
  intro: string;
  /**
   * Der Button verlinkt immer auf /kalender.
   */
  ctaLabel: string;
  leerTextVor: string;
  /**
   * Verlinkt auf /kalender.
   */
  leerLinkText: string;
  leerTextNach: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vorstand-section".
 */
export interface VorstandSection {
  id: number;
  eyebrow: string;
  headlineTeil1: string;
  headlineTeil2: string;
  intro: string;
  /**
   * Der Button verlinkt immer auf /vorstand.
   */
  ctaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-section".
 */
export interface NewsSection {
  id: number;
  eyebrow: string;
  headlineTeil1: string;
  headlineTeil2: string;
  intro: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitgliedschaft_select".
 */
export interface MitgliedschaftSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        antragButtonLabel?: T;
        antragPdf?: T;
        kontaktLinkLabel?: T;
        kontaktEmail?: T;
      };
  vorteile?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        titelHinten?: T;
        text?: T;
        liste?:
          | T
          | {
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              wert?: T;
              label?: T;
              zusatz?: T;
              id?: T;
            };
      };
  dokumente?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        karten?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              datei?: T;
              downloadLabel?: T;
              mailLabel?: T;
              mailAdresse?: T;
              mailBetreff?: T;
              id?: T;
            };
      };
  prozess?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        schritte?:
          | T
          | {
              nr?: T;
              titel?: T;
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        titel?: T;
        text?: T;
        buttonLabel?: T;
        email?: T;
        telefonLabel?: T;
        telefonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training_select".
 */
export interface TrainingSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        buttonLabel?: T;
        telefonHref?: T;
      };
  trainer?:
    | T
    | {
        eyebrow?: T;
        foto?: T;
        badge?: T;
        name?: T;
        rolle?: T;
        bio?: T;
        fakten?:
          | T
          | {
              wert?: T;
              label?: T;
              id?: T;
            };
        telefonLabel?: T;
        telefonHref?: T;
      };
  angebote?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        karten?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              id?: T;
            };
      };
  halle?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        stats?:
          | T
          | {
              wert?: T;
              label?: T;
              id?: T;
            };
        websiteLabel?: T;
        websiteUrl?: T;
        anrufLabel?: T;
        telefonHref?: T;
        standortTitel?: T;
        adresse?: T;
        kontaktTitel?: T;
        kontaktText?: T;
        kontaktTelefonLabel?: T;
        kontaktTelefonHref?: T;
        kontaktEmail?: T;
      };
  cta?:
    | T
    | {
        titel?: T;
        text?: T;
        buttonLabel?: T;
        telefonHref?: T;
        zurueckLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eisstock_select".
 */
export interface EisstockSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        bild?: T;
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        buttonLabel?: T;
      };
  angebot?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        kacheln?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              id?: T;
            };
      };
  galerie?:
    | T
    | {
        bilder?:
          | T
          | {
              bild?: T;
              id?: T;
            };
      };
  buchung?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        widgetUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headline?: T;
  subtext?: T;
  ctaLabel?: T;
  bild?: T;
  partnerLogos?:
    | T
    | {
        logo?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-section_select".
 */
export interface WelcomeSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  intro?: T;
  stats?:
    | T
    | {
        icon?: T;
        wert?: T;
        label?: T;
        id?: T;
      };
  bild?: T;
  bildBadge?: T;
  text?: T;
  signaturName?: T;
  signaturRolle?: T;
  ctaLabel?: T;
  sekundaerLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-section_select".
 */
export interface LocationSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineTeil1?: T;
  headlineTeil2?: T;
  intro?: T;
  ctaLabel?: T;
  karten?:
    | T
    | {
        titel?: T;
        untertitel?: T;
        bild?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  vereinsname?: T;
  beschreibung?: T;
  strasse?: T;
  plz?: T;
  ort?: T;
  email?: T;
  telefonLabel?: T;
  telefon?: T;
  telefonHref?: T;
  kontaktpersonen?:
    | T
    | {
        label?: T;
        name?: T;
        email?: T;
        id?: T;
      };
  funFactTitel?: T;
  funFact?: T;
  shop?:
    | T
    | {
        textVor?: T;
        linkText?: T;
        url?: T;
        textNach?: T;
      };
  instagram?:
    | T
    | {
        handle?: T;
        url?: T;
        ctaEyebrow?: T;
        ctaHeadline?: T;
        ctaText?: T;
      };
  copyrightName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt-section_select".
 */
export interface KontaktSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineTeil1?: T;
  headlineTeil2?: T;
  intro?: T;
  mapsEmbedUrl?: T;
  mapsTitel?: T;
  erfolgTitel?: T;
  erfolgText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seiten-texte_select".
 */
export interface SeitenTexteSelect<T extends boolean = true> {
  vorstand?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        badgeSuffix?: T;
        gruppen?:
          | T
          | {
              gruppe?: T;
              titel?: T;
              beschreibung?: T;
              id?: T;
            };
        ctaTitel?: T;
        ctaText?: T;
        ctaButtonLabel?: T;
        ctaEmail?: T;
      };
  kalender?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        monatsansichtLabel?: T;
        listenansichtLabel?: T;
        filterAlleLabel?: T;
        ausgewaehlterTagLabel?: T;
        naechsteTermineLabel?: T;
        keineTermineTag?: T;
        keineTermineListe?: T;
        uhrzeitSuffix?: T;
      };
  galerie?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        bilderSuffix?: T;
        leerText?: T;
      };
  mannschaften?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        kategorien?:
          | T
          | {
              kategorie?: T;
              reiterLabel?: T;
              listenEyebrow?: T;
              badgeSuffix?: T;
              id?: T;
            };
        teamsSuffix?: T;
        kartenUntertitel?: T;
        kontaktEyebrow?: T;
        kontaktTitelVorne?: T;
        kontaktTitelHighlight?: T;
        kontaktText?: T;
        kontaktLabel?: T;
        kontaktTelefon?: T;
        kontaktTelefonHref?: T;
        kontaktEmail?: T;
      };
  mannschaftDetail?:
    | T
    | {
        zurueckLabel?: T;
        saisonLabel?: T;
        vereinBadge?: T;
        verbandBadge?: T;
        ligaEyebrow?: T;
        ligaTitel?: T;
        ligaSaisonLabel?: T;
        ligaQuelle?: T;
        abschlussText?: T;
      };
  rechtliches?:
    | T
    | {
        zurueckLabel?: T;
        cookiesEyebrow?: T;
        cookiesTitelVorne?: T;
        cookiesTitelHighlight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termine-section_select".
 */
export interface TermineSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineTeil1?: T;
  headlineTeil2?: T;
  intro?: T;
  ctaLabel?: T;
  leerTextVor?: T;
  leerLinkText?: T;
  leerTextNach?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vorstand-section_select".
 */
export interface VorstandSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineTeil1?: T;
  headlineTeil2?: T;
  intro?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-section_select".
 */
export interface NewsSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  headlineTeil1?: T;
  headlineTeil2?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}