/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    teams: Team;
    'board-members': BoardMember;
    events: Event;
    'gallery-albums': GalleryAlbum;
    news: News;
    'legal-pages': LegalPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    mitgliedschaft: Mitgliedschaft;
    training: Training;
    eisstock: Eisstock;
    hero: Hero;
  };
  globalsSelect: {
    mitgliedschaft: MitgliedschaftSelect<false> | MitgliedschaftSelect<true>;
    training: TrainingSelect<false> | TrainingSelect<true>;
    eisstock: EisstockSelect<false> | EisstockSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  slug: string;
  name: string;
  kategorie: 'Herren' | 'Damen' | 'Gemischt';
  kontakt: string;
  bild?: (number | null) | Media;
  ligaUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  titel: string;
  gruppe: 'fuehrung' | 'finanzen' | 'sport' | 'events' | 'technik';
  /**
   * Bestimmt die Reihenfolge innerhalb der Gruppe und auf der Startseite.
   */
  reihenfolge: number;
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  telefon?: string | null;
  foto?: (number | null) | Media;
  /**
   * Die ersten 3 Markierten (nach Reihenfolge) erscheinen auf der Startseite.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  titel: string;
  datum: string;
  datumEnde?: string | null;
  /**
   * z.B. "10:00" oder "Ganztägig"
   */
  uhrzeit?: string | null;
  ort?: string | null;
  kategorie: 'Training' | 'Turnier' | 'Sonstiges';
  beschreibung?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  /**
   * z.B. "Rückblick 2024" — erscheint als Überschrift über dem Bilderraster.
   */
  titel: string;
  /**
   * Bestimmt die Reihenfolge: neuestes Jahr zuerst.
   */
  jahr: number;
  /**
   * Die Reihenfolge hier ist die Reihenfolge auf der Website.
   */
  bilder: (number | Media)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  datum: string;
  titel: string;
  /**
   * Wird auf der Startseite unter der Überschrift angezeigt.
   */
  excerpt: string;
  /**
   * Wird aktuell noch nicht auf der Website angezeigt — eine Detailseite folgt in einem späteren Schritt.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bild?: (number | null) | Media;
  kategorie: 'Vereinsnews' | 'Vereinsleben' | 'Turnier' | 'Training';
  updatedAt: string;
  createdAt: string;
}
/**
 * Impressum, Datenschutzerklärung und Cookie-Seite. Diese drei Seiten können bearbeitet, aber nicht neu angelegt oder gelöscht werden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  /**
   * Fest verdrahtet — bestimmt die URL der Seite und kann nicht geändert werden.
   */
  slug: 'impressum' | 'datenschutz' | 'cookies';
  /**
   * Überschrift der Seite und Titel im Browser-Tab.
   */
  titel: string;
  /**
   * Optionaler Text direkt unter der Überschrift (wird auf der Cookie-Seite genutzt).
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Jeder Abschnitt erscheint als eigene Karte mit kleiner Überschrift darüber.
   */
  abschnitte?:
    | {
        titel: string;
        inhalt: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * z.B. "Stand: Juni 2026" — erscheint klein unter der Seite.
   */
  stand?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  kategorie?: T;
  kontakt?: T;
  bild?: T;
  ligaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  titel?: T;
  gruppe?: T;
  reihenfolge?: T;
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  telefon?: T;
  foto?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  titel?: T;
  datum?: T;
  datumEnde?: T;
  uhrzeit?: T;
  ort?: T;
  kategorie?: T;
  beschreibung?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  titel?: T;
  jahr?: T;
  bilder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  datum?: T;
  titel?: T;
  excerpt?: T;
  content?: T;
  bild?: T;
  kategorie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  titel?: T;
  intro?: T;
  abschnitte?:
    | T
    | {
        titel?: T;
        inhalt?: T;
        id?: T;
      };
  stand?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitgliedschaft".
 */
export interface Mitgliedschaft {
  id: number;
  hero: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    antragButtonLabel: string;
    /**
     * Wird vom Button im Hero heruntergeladen.
     */
    antragPdf?: (number | null) | Media;
    kontaktLinkLabel: string;
    kontaktEmail: string;
  };
  vorteile: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    titelHinten?: string | null;
    text: string;
    liste: {
      text: string;
      id?: string | null;
    }[];
    stats: {
      wert: string;
      label: string;
      zusatz: string;
      id?: string | null;
    }[];
  };
  dokumente: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    karten: {
      icon: 'users' | 'star' | 'fileText';
      titel: string;
      beschreibung: string;
      datei?: (number | null) | Media;
      downloadLabel: string;
      mailLabel?: string | null;
      mailAdresse?: string | null;
      mailBetreff?: string | null;
      id?: string | null;
    }[];
  };
  prozess: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    schritte: {
      nr: string;
      titel: string;
      text: string;
      id?: string | null;
    }[];
  };
  cta: {
    titel: string;
    text: string;
    buttonLabel: string;
    email: string;
    telefonLabel: string;
    /**
     * Wird als tel:-Link verwendet, z.B. "+4917225802099".
     */
    telefonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training".
 */
export interface Training {
  id: number;
  hero: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    buttonLabel: string;
    /**
     * Wird als tel:-Link verwendet, z.B. "+4917559049030".
     */
    telefonHref: string;
  };
  trainer: {
    eyebrow: string;
    foto?: (number | null) | Media;
    badge: string;
    name: string;
    rolle: string;
    /**
     * Leerzeile = neuer Absatz.
     */
    bio: string;
    fakten: {
      wert: string;
      label: string;
      id?: string | null;
    }[];
    telefonLabel: string;
    telefonHref: string;
  };
  angebote: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    karten: {
      icon: 'userCheck' | 'users' | 'trophy' | 'dumbbell' | 'star' | 'calendar';
      titel: string;
      beschreibung: string;
      id?: string | null;
    }[];
  };
  halle: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    stats: {
      wert: string;
      label: string;
      id?: string | null;
    }[];
    websiteLabel: string;
    websiteUrl: string;
    anrufLabel: string;
    telefonHref: string;
    standortTitel: string;
    /**
     * Jede Zeile wird als eigene Zeile ausgegeben.
     */
    adresse: string;
    kontaktTitel: string;
    kontaktText: string;
    kontaktTelefonLabel?: string | null;
    kontaktTelefonHref?: string | null;
    kontaktEmail?: string | null;
  };
  cta: {
    titel: string;
    text: string;
    buttonLabel: string;
    telefonHref: string;
    zurueckLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eisstock".
 */
export interface Eisstock {
  id: number;
  hero: {
    bild?: (number | null) | Media;
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    buttonLabel: string;
  };
  angebot: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    kacheln: {
      icon: 'mapPin' | 'users' | 'euro' | 'calendarDays';
      titel: string;
      beschreibung: string;
      id?: string | null;
    }[];
  };
  galerie?: {
    bilder?:
      | {
          bild: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  buchung: {
    eyebrow: string;
    titelVorne: string;
    titelHighlight: string;
    text: string;
    /**
     * Wird als Buchungs-Widget (iframe) eingebunden.
     */
    widgetUrl: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  headline: string;
  subtext: string;
  /**
   * Der Button verlinkt immer auf /mitgliedschaft.
   */
  ctaLabel: string;
  /**
   * Querformat, mindestens 1920×1080. Ohne Bild bleibt die Fläche grau — die Seite bricht nicht.
   */
  bild?: (number | null) | Media;
  /**
   * Laufen als Endlosband unter dem Text durch.
   */
  partnerLogos?:
    | {
        logo: number | Media;
        /**
         * Leer lassen = Alternativtext des Bildes wird verwendet.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitgliedschaft_select".
 */
export interface MitgliedschaftSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        antragButtonLabel?: T;
        antragPdf?: T;
        kontaktLinkLabel?: T;
        kontaktEmail?: T;
      };
  vorteile?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        titelHinten?: T;
        text?: T;
        liste?:
          | T
          | {
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              wert?: T;
              label?: T;
              zusatz?: T;
              id?: T;
            };
      };
  dokumente?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        karten?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              datei?: T;
              downloadLabel?: T;
              mailLabel?: T;
              mailAdresse?: T;
              mailBetreff?: T;
              id?: T;
            };
      };
  prozess?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        schritte?:
          | T
          | {
              nr?: T;
              titel?: T;
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        titel?: T;
        text?: T;
        buttonLabel?: T;
        email?: T;
        telefonLabel?: T;
        telefonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training_select".
 */
export interface TrainingSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        buttonLabel?: T;
        telefonHref?: T;
      };
  trainer?:
    | T
    | {
        eyebrow?: T;
        foto?: T;
        badge?: T;
        name?: T;
        rolle?: T;
        bio?: T;
        fakten?:
          | T
          | {
              wert?: T;
              label?: T;
              id?: T;
            };
        telefonLabel?: T;
        telefonHref?: T;
      };
  angebote?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        karten?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              id?: T;
            };
      };
  halle?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        stats?:
          | T
          | {
              wert?: T;
              label?: T;
              id?: T;
            };
        websiteLabel?: T;
        websiteUrl?: T;
        anrufLabel?: T;
        telefonHref?: T;
        standortTitel?: T;
        adresse?: T;
        kontaktTitel?: T;
        kontaktText?: T;
        kontaktTelefonLabel?: T;
        kontaktTelefonHref?: T;
        kontaktEmail?: T;
      };
  cta?:
    | T
    | {
        titel?: T;
        text?: T;
        buttonLabel?: T;
        telefonHref?: T;
        zurueckLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eisstock_select".
 */
export interface EisstockSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        bild?: T;
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        buttonLabel?: T;
      };
  angebot?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        kacheln?:
          | T
          | {
              icon?: T;
              titel?: T;
              beschreibung?: T;
              id?: T;
            };
      };
  galerie?:
    | T
    | {
        bilder?:
          | T
          | {
              bild?: T;
              id?: T;
            };
      };
  buchung?:
    | T
    | {
        eyebrow?: T;
        titelVorne?: T;
        titelHighlight?: T;
        text?: T;
        widgetUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headline?: T;
  subtext?: T;
  ctaLabel?: T;
  bild?: T;
  partnerLogos?:
    | T
    | {
        logo?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}